added dialog for reject btn
MSU-Students/student-advising-portal pull request #34
Opened 2024-11-30 12:57 UTC by MantokKa

Added a dialog for reject btn.

2024-11-30 13:01 UTC, 29-29 requested changes
move dialog to a separate component please

2024-11-30 14:14 UTC, lavahotsnacks commented
> move dialog to a separate component please

wow we had the same idea

2024-11-30 14:20 UTC, lavahotsnacks commented
> move dialog to a separate component please

2024-11-30 14:25 UTC, lavahotsnacks commented
accidentally closed the pr, my bad

2024-11-30 23:44 UTC, fencim requested changes

2024-11-30 23:44 UTC, fencim commented on src/components/admin/RejectDialog.vue
You may want to move this dialogs under /src/dialogs/admin/

2024-11-30 23:44 UTC, fencim commented on src/components/admin/RejectDialog.vue
> +};
You may want to use TheDialogs Api referring from other existing dialogs

2024-12-02 04:24 UTC, 29-29 requested changes
please check the suggested changes

2024-12-02 04:24 UTC, 29-29 commented on src/dialogs/admin/RejectDialog.vue
> +      style="border-radius: 15px; background-color: black"
change the background using quasar style classes
```suggestion
      class="q-pa-md bg-white rounded-borders"
```

2024-12-02 04:24 UTC, 29-29 commented on src/dialogs/admin/RejectDialog.vue
> +        <div class="text-h6 text-white">
to conform to white background
```suggestion
        <div class="text-h6">
```

2024-12-02 05:36 UTC, 29-29 approved these changes
this is ok na

2024-12-02 06:10 UTC, lavahotsnacks approved these changes
ok

2024-12-02 06:15 UTC, 29-29 approved these changes

2024-12-03 12:09 UTC, lavahotsnacks commented
sir @fencim, can you please approve this pull request.

2024-12-04 00:48 UTC, fencim approved these changes

2024-12-04 00:49 UTC, merged